[package]
name = "reward_system"
version = "0.1.0"
edition = "2023_11"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = ">=2.3.1"

[scripts]
test = "scarb test"

sierra = "true"
casm = "true"

[[target.starknet-contract]]
